### ISSUE TITLE
.scrapekit.ini

### ISSUE THREAD

**Issue by ramesh-kc** [pudo-attic/scrapekit#2]
[scrapekit]
reports_path = /var/www/scrapers/reports
[craigslist-sf-boats]
threads = 10
cache_policy =  http
data_path =  data
how can i pass this setting to the scrape_boats.py .py file, which create the cache inside the data folder. But, when doing this 
config = {
  'threads': 10,
  'cache_policy': 'http',
  'data_path': 'data'
}
scraper = scrapekit.Scraper('craigslist-sf-boats',config = config) i
it works fine.

**Comment by scottwar34** [comment]
Hi I just installed the scrapekit by the repository from GitHub.
 I am trying to run the example file, scraper for postings on Craigslist, and it isn't running correctly, i'm getting this error syntax: craigslist-sf-boats [ERROR   ]: No module named lxml. can you please explain to me what is problem? Or what I missed?

**Comment by pudo** [comment]
Sorry, I don't have the time to provide support for old software that is no longer maintained. You seem to not have lxml installed.
